language: php

php:
  - 7.3
  - 7.4
  - 8

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - benjaminserfhos@hotmail.com
    on_success: change
    on_failure: change

before_script:
  - Build/Scripts/tests.sh -s composerInstall -p $TRAVIS_PHP_VERSION

script:
  - >
    echo "Running composer validate"
    Build/Scripts/tests.sh -s composerValidate -p $TRAVIS_PHP_VERSION

  - >
    echo "Running unit tests";
    Build/Scripts/tests.sh -s unit -p $TRAVIS_PHP_VERSION

  - >
    echo "Running php lint";
    Build/Scripts/tests.sh -s lint -p $TRAVIS_PHP_VERSION
